name: Deploy Application

on:
  push:
    branches: [main]

jobs:

  codeql-scan:
    uses: genzitizens/ci-templates/.github/workflows/codeql.yml@main
    with:
      languages: '["java"]'
      codeql-cfg-path: ".github/codeql-config.yml" # optional
      build-command: |
        ./mvnw clean install

  sonarcloud-scan:
    uses: genzitizens/ci-templates/.github/workflows/sonarcloud.yml@main
    with:
      projectBaseDir: "." # optional if using default
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  containerizing:
    needs: 
      - sonarcloud-scan
      - codeql-scan
    uses: genzitizens/ci-templates/.github/workflows/springboot-push-to-ghcr.yml@main
    with:
      image_name: keycloak-demo
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_ORG: ${{ secrets.GHCR_ORG }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  LIVE-Deployment:
    needs: push-ghcr
    uses: genzitizens/ci-templates/.github/workflows/deploy-to-vps.yml@main
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      GHCR_ORG: ${{ secrets.GHCR_ORG }}

    with:
      IMAGE_NAME: "keycloak-demo"
      COMPOSE_PATH: "/home/exeltan/keycloak-demo/docker-compose.yml"